version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo login to ecr `aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 584315761995.dkr.ecr.us-east-1.amazonaws.com`..
      - REPOSITORY_URI=584315761995.dkr.ecr.us-east-1.amazon.com/mynewcustomecr.
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Maven Application using war file..
      - mvn install
      - echo Building the Docker image...
      - docker build -t 584315761995.dkr.ecr.us-east-1.amazon.com/mynewcustomecr:latest .
      - docker tag 584315761995.dkr.ecr.us-east-1.amazon.com/mynewcustomecr:latest 584315761995.dkr.ecr.us-east-1.amazon.com/mynewcustomecr:v1
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Build successfully generated a war file
      - echo Pushing the Docker images...
      
      - echo successfully build docker image and send to aws ecr.
artifacts:
  files:
    - target/maven-web-application.war
