---
- name: Create a websever
  hosts: all
  become: true
  become_method: sudo
  gather_facts:  yes
  tasks:
    - name: Create a file
      file:
        path: /root/mycustomfile1
        owner: root
        become: true
        group: root
        state: touch
        mode: '0777'
    
    - name: create a another file
      file:
        path: /root/mynewfile
        become: true
        owner: root
        group: root
        state: touch
        mode: '0777'
        
